# frozen_string_literal: true

require 'spec_helper'

RSpec.describe GoogleAPI::Calendar do
  def test_event
    {
      summary: 'API Test Event',
      description: 'This is a test event generated by the API gem.',
      start: DateTime.strptime('201906051200', '%Y%m%d%H%M'),
      end: DateTime.strptime('201906051400', '%Y%m%d%H%M')
    }
  end

  describe 'service class' do
    subject { described_class.new }

    it 'does not raise an error' do
      expect { subject.send(:service_class) }.not_to raise_error
    end

    it 'is the correct class' do
      expect(subject.send(:service_class)).to eql(Google::Apis::CalendarV3::CalendarService)
    end
  end

  context 'with an invalid calendar' do
    let(:test_cal_id) { 'not-a-calendar' }

    subject { GoogleAPI::Configured::Calendar.new(test_cal_id) }

    it 'returns not found from list' do
      expect { subject.list }.to raise_error(
        Google::Apis::ClientError, 'notFound: Not Found'
      )
    end

    it 'returns not found from create' do
      expect { subject.create }.to raise_error(
        Google::Apis::ClientError, 'notFound: Not Found'
      )
    end

    it 'returns not found from get' do
      expect { subject.get('not-an-event') }.to raise_error(
        Google::Apis::ClientError, 'notFound: Not Found'
      )
    end

    it 'returns not found from update' do
      expect { subject.update('not-an-event') }.to raise_error(
        Google::Apis::ClientError, 'notFound: Not Found'
      )
    end

    it 'returns event not found from delete' do
      expect(subject.delete('not-an-event')).to eql(
        :event_not_found
      )
    end

    it 'returns nil from permit' do
      expect(subject.permit(email: 'not-a-user')).to be_nil
    end

    it 'returns permission not found from unpermit' do
      expect(subject.unpermit(calendar_rule_id: 'not-a-user')).to eql(:permission_not_found)
    end
  end

  context 'with a valid calendar' do
    let(:test_cal_id) { ENV['GOOGLE_CALENDAR_ID_TEST'] }

    subject { GoogleAPI::Configured::Calendar.new(test_cal_id) }

    it 'returns a list' do
      expect(subject.list).to be_a(Google::Apis::CalendarV3::Events)
    end

    it 'creates an event' do
      expect(subject.create(test_event)).to be_a(Google::Apis::CalendarV3::Event)
    end

    it 'gets an event ' do
      event = subject.create(test_event)
      expect(subject.get(event.id)).to be_a(Google::Apis::CalendarV3::Event)
    end

    it 'updates an event' do
      event = subject.create(test_event)
      updated_test_event = test_event.merge(description: 'Updated.')
      subject.update(event.id, updated_test_event)
      updated_event = subject.get(event.id)

      expect(updated_event.description).to eql('Updated.')
    end

    it 'deletes an event' do
      event = subject.create(test_event)

      expect(subject.delete(event.id)).to eql('')
    end

    it 'returns nil from permit' do
      expect(subject.permit(email: 'not-a-user')).to be_nil
    end

    it 'returns permission not found from unpermit' do
      expect(subject.unpermit(calendar_rule_id: 'not-a-user')).to eql(:permission_not_found)
    end

    describe 'clear test calendar' do
      it 'does not raise any errors' do
        expect { subject.clear_test_calendar }.not_to raise_error
      end

      it 'rescues from an unhandled rate limit exception' do
        expect { subject.clear_test_calendar(error: true) }.not_to raise_error
      end

      it 'does not raise any errors with verbose' do
        subject.create(test_event)

        silently do
          expect do
            GoogleAPI::Configured::Calendar.new('test').clear_test_calendar(verbose: true)
          end.not_to raise_error
        end
      end
    end
  end
end
